[tool.black]
line-length = 100
target-version = ['py36']

# Black compatible configuration
[tool.isort]
line_length = 100
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
